-- creates databases MyLib
CREATE DATABASE IF NOT EXISTS MyLib;
USE MyLib;
CREATE TABLE IF NOT EXISTS Books(
   ISBN VARCHAR(25) NOT NULL PRIMARY KEY,
   title VARCHAR(256) NOT NULL,
   author VARCHAR(50) NOT NULL,
   editor VARCHAR(50) NOT NULL,
   release_date VARCHAR(50) NOT NULL,
   couverture VARCHAR(256)
);
CREATE TABLE Users(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(256) UNIQUE NOT NULL,
   mail VARCHAR(256) UNIQUE NOT NULL,
   password VARCHAR(64) NOT NULL,
   jwt_token VARCHAR(256)
);
CREATE TABLE Status(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   status CHAR(8) NOT NULL
);
CREATE TABLE User_books(
   user_ID INT,
   book_ID VARCHAR(25),
   status_ID INT,
   FOREIGN KEY(user_ID) REFERENCES Users(ID),
   FOREIGN KEY(book_ID) REFERENCES Books(ISBN),
   FOREIGN KEY(status_ID) REFERENCES Status(ID)
);
